garnet: fixup! ims: Remove MIUI dependencies
From the previous commit (43e92de), the
synchronizeMessage definition got removed entirely from
ImsSenderRxr.smali. However, the synchronizeMessage method got called
anyway from ImsCallSessionImpl.smali and
ImsCallSessionImpl$ImsCallSessionImplHandler.smali, causing the
following crashes:

FATAL EXCEPTION: main
Process: org.codeaurora.ims, PID: 3363
java.lang.NoSuchMethodError: No virtual method synchronizeMessage(Ljava/lang/String;II)V in class Lorg/codeaurora/ims/ImsSenderRxr; or its super classes (declaration of 'org.codeaurora.ims.ImsSenderRxr' appears in /system_ext/priv-app/ims/ims.apk)
 at org.codeaurora.ims.ImsCallSessionImpl$ImsCallSessionImplHandler.handleMessage(ImsCallSessionImpl.java:1125)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8488)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

This patch also fixes the ended call problem where the ongoing call gets
ended after rejecting an incoming call at the same time.

Testing: https://github.com/truly-irham/ims/releases/download/v1.0/fix_ims_crash-v1.zip